#! /bin/bash
wget http://api.usno.navy.mil/imagery/moon.png -O rawmoon.png
convert rawmoon.png -trim -resize 150x150\! moon.png
convert moon.png /home/lee/ap/static/maske.png -alpha Off -compose CopyOpacity -composite /home/lee/www/arlplanet/currentmoon.png
chmod 644 /home/lee/www/arlplanet/currentmoon.png
